# =============================================================================
# Remote Terraform state backend (security review T1.2, design v2.8)
# =============================================================================
#
# State lives in Hetzner Object Storage (S3-compatible). Closes the
# "operator laptop is the only home of terraform.tfstate" risk that the
# 2026-05-15 security review opened.
#
# The empty `s3 {}` block below is INTENTIONAL — Terraform calls this
# "partial configuration". Operator-specific values (bucket name, region,
# endpoint, S3 credentials) are supplied at `terraform init` time from
# `backend.tfbackend`, which is generated by:
#
#   python scripts/seed_bootstrap.py seed.yaml --target tf-backend
#
# Init command:
#
#   terraform init -backend-config=backend.tfbackend
#
# The `backend.tfbackend` file is gitignored (it contains S3 credentials).
#
# The `skip_*` and `use_path_style` flags below are universal "this is a
# non-AWS S3 implementation" settings — they disable AWS-metadata-API
# behaviour that doesn't exist on Hetzner Object Storage. Not operator-
# specific, so they live here (committed) rather than in the .tfbackend.
#
# `encrypt = true` enables server-side encryption (SSE-S3) at Hetzner.
# Hetzner manages the keys; protects against raw-disk read of the bucket
# storage. For client-side encryption, the offline-kit snapshot is the
# defence — bucket SSE alone does not protect against Hetzner-the-company.

terraform {
  backend "s3" {
    # All operator-supplied values come from backend.tfbackend:
    #   bucket, key, region, endpoints, access_key, secret_key
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_s3_checksum            = true
    use_path_style              = true
    encrypt                     = true
  }
}
