#!/usr/bin/env python3
"""Bootstrap tool: read seed.yaml and generate all downstream config files.

Usage:
    python scripts/seed_bootstrap.py seed.yaml --validate
    python scripts/seed_bootstrap.py seed.yaml --target all
    python scripts/seed_bootstrap.py seed.yaml --target terraform --diff
    python scripts/seed_bootstrap.py seed.yaml --target borg-conf --force
"""

from __future__ import annotations

import argparse
import difflib
import sys
import textwrap
from pathlib import Path

import yaml

# Allow running from project root: ``python scripts/seed_bootstrap.py``
_SCRIPTS_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPTS_DIR.parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from seed_schema import SeedConfig  # noqa: E402

# ---------------------------------------------------------------------------
# Target registry
# ---------------------------------------------------------------------------

TARGETS = ("terraform", "borg-conf", "s3-conf")


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------


def _generate_terraform_tfvars(seed: SeedConfig) -> str:
    """Generate terraform/terraform.tfvars content."""
    infra = seed.infrastructure
    org = seed.organization

    ssh_keys_block = "{\n"
    for name, key in infra.ssh.admin_keys.items():
        ssh_keys_block += f'  "{name}" = "{key}"\n'
    ssh_keys_block += "}"

    trusted_ips_block = "[\n"
    for ip in infra.ssh.trusted_ips:
        trusted_ips_block += f'  "{ip}",\n'
    trusted_ips_block += "]"

    labels_block = "{\n"
    for k, v in org.labels.items():
        labels_block += f'  {k} = "{v}"\n'
    labels_block += f'  env = "{org.environment}"\n'
    labels_block += "}"

    return textwrap.dedent(f"""\
        # Generated by seed_bootstrap.py — do not edit manually
        # Re-generate: python scripts/seed_bootstrap.py seed.yaml --target terraform

        hcloud_token = "{infra.hetzner.api_token}"

        domain      = "{seed.gitlab.domain}"
        admin_email = "{org.admin_email}"

        ssh_public_keys = {ssh_keys_block}

        trusted_ssh_ips = {trusted_ips_block}

        storage_box_host = "{seed.backup.storage_box.host}"
        storage_box_user = "{seed.backup.storage_box.user}"

        gitlab_server_type = "{infra.servers.gitlab.type}"
        server_image       = "{infra.servers.gitlab.image}"
        location           = "{infra.hetzner.location}"

        gitlab_data_volume_size   = {infra.storage.gitlab_data_volume_gb}
        gitlab_backup_volume_size = {infra.storage.gitlab_backup_volume_gb}

        network_cidr = "{infra.network.cidr}"
        subnet_cidr  = "{infra.network.subnet_cidr}"

        gitlab_private_ip = "{infra.servers.gitlab.private_ip}"

        common_labels = {labels_block}

        environment = "{org.environment}"
    """)


def _generate_borg_conf(seed: SeedConfig) -> str:
    """Generate /etc/gitlab-backup.conf content (shell exports)."""
    ret = seed.backup.retention
    lines = [
        "# Generated by seed_bootstrap.py — do not edit manually",
        "# Re-generate: python scripts/seed_bootstrap.py seed.yaml --target borg-conf",
        "# Source this file in backup scripts: . /etc/gitlab-backup.conf",
        "",
        f'export BORG_REPO="{seed.borg_repo}"',
        f'export BORG_PASSPHRASE="{seed.backup.borg.passphrase}"',
        'export BORG_RSH="ssh -i /root/.ssh/storagebox_key -o StrictHostKeyChecking=accept-new -p 23"',
        "",
        f"export BACKUP_KEEP_HOURLY={ret.keep_hourly}",
        f"export BACKUP_KEEP_DAILY={ret.keep_daily}",
        f"export BACKUP_KEEP_WEEKLY={ret.keep_weekly}",
        f"export BACKUP_KEEP_MONTHLY={ret.keep_monthly}",
        "",
    ]
    return "\n".join(lines)


def _generate_s3_conf(seed: SeedConfig) -> str:
    """Generate /etc/gitlab-s3-backup.conf content (shell exports)."""
    s3 = seed.backup.s3
    if not s3.enabled:
        return (
            "# S3 immutable backup is DISABLED in seed config.\n"
            "# Set backup.s3.enabled: true in seed.yaml to enable.\n"
        )
    lines = [
        "# Generated by seed_bootstrap.py — do not edit manually",
        "# Re-generate: python scripts/seed_bootstrap.py seed.yaml --target s3-conf",
        "# Source this file in backup-to-s3.sh: . /etc/gitlab-s3-backup.conf",
        "",
        f'export S3_ENDPOINT="{s3.endpoint}"',
        f'export S3_BUCKET="{s3.bucket}"',
        f'export AWS_ACCESS_KEY_ID="{s3.access_key}"',
        f'export AWS_SECRET_ACCESS_KEY="{s3.secret_key}"',
        f"export S3_RETENTION_DAYS={s3.retention_days}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File output paths (relative to project root)
# ---------------------------------------------------------------------------

_TARGET_PATHS: dict[str, str | None] = {
    "terraform": "terraform/terraform.tfvars",
    "borg-conf": None,  # stdout only
    "s3-conf": None,  # stdout only
}

_GENERATORS: dict[str, object] = {
    "terraform": _generate_terraform_tfvars,
    "borg-conf": _generate_borg_conf,
    "s3-conf": _generate_s3_conf,
}


# ---------------------------------------------------------------------------
# Diff / write helpers
# ---------------------------------------------------------------------------


def _show_diff(path: Path, new_content: str) -> bool:
    """Print unified diff. Return True if content differs."""
    if path.exists():
        old = path.read_text()
    else:
        old = ""
    if old == new_content:
        return False
    diff = difflib.unified_diff(
        old.splitlines(keepends=True),
        new_content.splitlines(keepends=True),
        fromfile=str(path),
        tofile=str(path) + " (generated)",
    )
    sys.stdout.writelines(diff)
    return True


def _write_file(path: Path, content: str, *, force: bool) -> None:
    """Write content to path, prompting if file exists and --force not set."""
    if path.exists() and not force:
        if not _show_diff(path, content):
            print(f"  {path} — unchanged, skipping")
            return
        answer = input(f"\n  Overwrite {path}? [y/N] ").strip().lower()
        if answer != "y":
            print(f"  {path} — skipped")
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  {path} — written")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate downstream config files from seed.yaml.",
    )
    parser.add_argument(
        "seed_file",
        type=Path,
        help="Path to seed.yaml",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate seed.yaml and exit (no file generation)",
    )
    parser.add_argument(
        "--target",
        choices=[*TARGETS, "all"],
        help="Which config to generate",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Show diff of what would change, without writing",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files without prompting",
    )
    return parser


def _load_seed(path: Path) -> SeedConfig:
    """Load and validate seed.yaml, exiting on error."""
    if not path.exists():
        print(f"Error: {path} not found", file=sys.stderr)
        sys.exit(1)

    with open(path) as f:
        raw = yaml.safe_load(f)

    if not isinstance(raw, dict):
        print(f"Error: {path} is not a valid YAML mapping", file=sys.stderr)
        sys.exit(1)

    try:
        return SeedConfig(**raw)
    except Exception as exc:
        print(f"Validation error: {exc}", file=sys.stderr)
        sys.exit(1)


def main(argv: list[str] | None = None) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)

    seed = _load_seed(args.seed_file)
    print(f"Seed v{seed.version} loaded — {seed.organization.name} ({seed.organization.environment})")

    if args.validate:
        print("Validation passed.")
        return

    if not args.target:
        parser.error("--target is required when not using --validate")

    targets = list(TARGETS) if args.target == "all" else [args.target]

    for target in targets:
        generator = _GENERATORS[target]
        assert callable(generator)
        content: str = generator(seed)  # type: ignore[operator]
        rel_path = _TARGET_PATHS[target]

        if rel_path is None:
            # stdout target (borg-conf)
            if args.diff:
                print(f"\n--- {target} (stdout) ---")
                print(content)
            else:
                print(f"\n--- {target} ---")
                print(content)
            continue

        out_path = _PROJECT_ROOT / rel_path

        if args.diff:
            changed = _show_diff(out_path, content)
            if not changed:
                print(f"  {out_path} — unchanged")
        else:
            _write_file(out_path, content, force=args.force)


if __name__ == "__main__":
    main()
